version: '3'
services:

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
    command: ["npm","i","&&","npm","run","dev"]

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/app
    environment:
      - PORT=3000
    command: ["npm","run","dev"]